" Set mapleader.
let mapleader = " "
:inoremap jk <esc>

" Edit vimrc in vertical split.
:nnoremap <leader>ev :vsplit $MYVIMRC<cr>

" Source vimrc.
:nnoremap <leader>sv :source $MYVIMRC<cr>

" Edit pannotes.md
" :nnoremap <leader>ei :vsplit ~/pan/ideas.md<cr>
:nnoremap <leader>ei :e ~/pan/ideas.md<cr>

" Toggle Explore - Split left.
:nnoremap <leader>fe :Lexplore<cr> 

colorscheme darkblue
syntax on
filetype plugin indent on

set laststatus=2
set number
set termguicolors
set wildmenu

set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Installed Plugins
" ~/dotfiles/.vim/pack/panarcadia/start/
"
" vim-commentary
" vim-airline
