" Set mapleader.
let mapleader = " "
:inoremap jk <esc>

" Edit vimrc in vertical split.
:nnoremap <leader>ev :vsplit $MYVIMRC<cr>

" Source vimrc.
:nnoremap <leader>sv :source $MYVIMRC<cr>

" Edit pannotes.md
:nnoremap <leader>ei :vsplit ~/pan/pannotes/ideas.md<cr>

colorscheme darkblue
syntax on
filetype plugin indent on

set laststatus=2
set number
set termguicolors
set wildmenu

set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
